### ISSUE TITLE
Is new version for Vertica-Extension-Packages available???

### ISSUE THREAD

**Issue by vishal08jan** [vertica/Vertica-Extension-Packages#37]
We have upgraded our  vertica cluster from 7.1.0-1 to 7.1.1-7.

We had all the Vertica Extension Packages installed before the upgrade but all these packages are not working right now.
To counter this I tried recompiling the already present packages but are getting errors. Errors :

##############################################################################

vsql:/home/dbadmin/package/Vertica-Extension-Packages-master/strings_package/ddl/install.sql:4: ROLLBACK 4213:  Object "StringsLib" already exists
vsql:/home/dbadmin/package/Vertica-Extension-Packages-master/strings_package/ddl/install.sql:6: ROLLBACK 3857:  Library built with unsupported version of Vertica SDK [Version: v7.1.0-1, Revision: 142176]
HINT:  Expected version: [Version: v7.1.1-7, Revision: 155183]
vsql:/home/dbadmin/package/Vertica-Extension-Packages-master/strings_package/ddl/install.sql:7: ROLLBACK 3857:  Library built with unsupported version of Vertica SDK [Version: v7.1.0-1, Revision: 142176]
HINT:  Expected version: [Version: v7.1.1-7, Revision: 155183]
vsql:/home/dbadmin/package/Vertica-Extension-Packages-master/strings_package/ddl/install.sql:8: ROLLBACK 3857:  Library built with unsupported version of Vertica SDK [Version: v7.1.0-1, Revision: 142176]
HINT:  Expected version: [Version: v7.1.1-7, Revision: 155183]
vsql:/home/dbadmin/package/Vertica-Extension-Packages-master/strings_package/ddl/install.sql:9: ROLLBACK 3857:  Library built with unsupported version of Vertica SDK [Version: v7.1.0-1, Revision: 142176]
HINT:  Expected version: [Version: v7.1.1-7, Revision: 155183]
vsql:/home/dbadmin/package/Vertica-Extension-Packages-master/strings_package/ddl/install.sql:10: ROLLBACK 3857:  Library built with unsupported version of Vertica SDK [Version: v7.1.0-1, Revision: 142176]
HINT:  Expected version: [Version: v7.1.1-7, Revision: 155183]
vsql:/home/dbadmin/package/Vertica-Extension-Packages-master/strings_package/ddl/install.sql:11: ROLLBACK 3857:  Library built with unsupported version of Vertica SDK [Version: v7.1.0-1, Revision: 142176]
HINT:  Expected version: [Version: v7.1.1-7, Revision: 155183]
vsql:/home/dbadmin/package/Vertica-Extension-Packages-master/strings_package/ddl/install.sql:12: ROLLBACK 3857:  Library built with unsupported version of Vertica SDK [Version: v7.1.0-1, Revision: 142176]
HINT:  Expected version: [Version: v7.1.1-7, Revision: 155183]
vsql:/home/dbadmin/package/Vertica-Extension-Packages-master/strings_package/ddl/install.sql:13: ROLLBACK 3857:  Library built with unsupported version of Vertica SDK [Version: v7.1.0-1, Revision: 142176]
HINT:  Expected version: [Version: v7.1.1-7, Revision: 155183]
vsql:/home/dbadmin/package/Vertica-Extension-Packages-master/strings_package/ddl/install.sql:14: ROLLBACK 3857:  Library built with unsupported version of Vertica SDK [Version: v7.1.0-1, Revision: 142176]
HINT:  Expected version: [Version: v7.1.1-7, Revision: 155183]
vsql:/home/dbadmin/package/Vertica-Extension-Packages-master/strings_package/ddl/install.sql:15: ROLLBACK 3857:  Library built with unsupported version of Vertica SDK [Version: v7.1.0-1, Revision: 142176]
HINT:  Expected version: [Version: v7.1.1-7, Revision: 155183]
vsql:/home/dbadmin/package/Vertica-Extension-Packages-master/strings_package/ddl/install.sql:16: ROLLBACK 3857:  Library built with unsupported version of Vertica SDK [Version: v7.1.0-1, Revision: 142176]
HINT:  Expected version: [Version: v7.1.1-7, Revision: 155183]

##############################################################################
Can you please let us know if the new version of Vertica Extension Package is available for use.If yes, please share the link as well.

**Comment by aseering** [comment]
Hi -- are you asking about the Marketplace packages?  Github is source-code-only.  The source code on github should work just fine with Vertiva v7.1.1-7.

To compile the source code and get an updated binary, you must have a compiler and other common dev tools installed on a node in your cluster (or a machine running a similar Linux distribution to the nodes in your cluster with the Vertica Community Edition installed); then run "make".

If you would like help with getting updated binaries, and you are an Enterprise customer, you're welcome to get in contact with Vertica Customer Support through http://my.vertica.com/ .
