### ISSUE TITLE
lib/HeatMapLib.so file not found

### ISSUE THREAD

**Issue by smlcngl** [vertica/Vertica-Extension-Packages#41]
Could you please add more info about installation ? I am getting below error:

[dbadmin@localhost heatmap_package]$ make install
vsql -f ddl/install.sql
              version
------------------------------------
 Vertica Analytic Database v7.1.2-0
(1 row)

vsql:ddl/install.sql:5: ROLLBACK 3855:  Library "HeatMapFunctions" does not exist
vsql:ddl/install.sql:9: ROLLBACK 3399:  Failure in UDx RPC call InvokeSetExecContext(): Error calling setupExecContext() in User Defined Object [] at [/scratch_a/release/16125/vbuild/vertica/OSS/UDxFence/vertica-udx-C++.cpp:195], error code: 0, message: Error happened in dlopen(): [/home/dbadmin/verticaGithub/heatmap_package/lib/HeatMapLib.so: cannot open shared object file: No such file or directory]
vsql:ddl/install.sql:13: ROLLBACK 3861:  Library not found: HeatMapFunctions
vsql:ddl/install.sql:16: ROLLBACK 3861:  Library not found: HeatMapFunctions

**Comment by aseering** [comment]
Hi -- the conventional use of makefiles is to run "make" to compile the application, then "make install" to install it.  (Sometimes "make install" will automatically call "make" for you if you haven't already done so, but that's not guaranteed to be the case.)

Have you tried this?  If so, could you post the output of "make"?

**Comment by smlcngl** [comment]
Thanks using only make and after make install worked

**Comment by aseering** [comment]
I've updated the README to clarify that building (running "make") is required if you got the source code for this package from Github directly.

The package is also available in binary form for some Vertica versions, basically meaning that we already ran "make" for you, from the Vertica Marketplace (now known as the HP Haven Marketplace) -- https://haven.hpwsportal.com/
